# Generated by Django 2.0 on 2017-12-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('monto_letras', models.CharField(max_length=100)),
            ],
        ),
    ]
