# Generated by Django 2.0 on 2017-12-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_factura_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='monto_letras',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
