# Generated by Django 2.0 on 2017-12-19 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_auto_20171219_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='monto_letras',
            new_name='monto_palabras',
        ),
    ]
