# Generated by Django 2.0 on 2017-12-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_auto_20171219_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='concepto',
            field=models.TextField(max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
